### ISSUE TITLE
Updater for Citra.

### ISSUE THREAD

**Issue by DucAnhNguyen1997** [citra-valentin/citra#457]
Hello, I have a question about the latest Citra release (e3640fc). After awhile, I noticed that both mingw and msvc version has no updates, so I headed to the your release page and found out that the latest release name is "citra-windows-x64-20180926-e3640fc.zip", which has neither "mingw"  and "msvc" on its name.

I downloaded it, used it as usual, but I couldn't use the updater anymore. How should I edit the updater.cfg to make the updater again? Thanks.

**Comment by DucAnhNguyen1997** [comment]
So for now to update citra, I'll have to head to the release page and download it manually? Is there any other way to update it automatically?

**Comment by valentinvanelslande** [comment]
do whatever you want with the updater

**Comment by Ninjistix** [comment]
@DucAnhNguyen1997 can you post a gist of the update script, i lost the older version i had.
