### ISSUE TITLE
Just crashing without error.

### ISSUE THREAD

**Issue by powerofgreed** [citra-valentin/citra#461]
All latest build begining with (head-mingw 711) just crashing in random time. Playing MHxx. Trying to open settings - crash. Something load in game - crash....
Stayed on (#708) working fine without any crashing with 6+  hours of working.

**Comment by powerofgreed** [comment]
[citra_log.txt](https://github.com/citra-valentin/citra/files/2452776/citra_log.txt)
sorry for my English.

**Comment by powerofgreed** [comment]
728 working fine. Thx. good work!

**Comment by powerofgreed** [comment]
nvm... still crashing some times if i trying to open settings.
[citra_log.txt](https://github.com/citra-valentin/citra/files/2454742/citra_log.txt)

**Comment by valentinvanelslande** [comment]
disable `enable_clear_cache` in .ini file (File -> Open User Directory -> config -> qt-config.ini)
