### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Maxdex6** [citra-valentin/citra#466]
Hola tengo este error al querer abrir el ultra sol, solo me pasa con ese juego y me da este error:
![captura](https://user-images.githubusercontent.com/42588598/46983605-a3c52900-d0b7-11e8-87c1-2d4a98b39f84.PNG)

me podrian decir que hacer?

**Comment by Maxdex6** [comment]
[log.txt](https://github.com/citra-valentin/citra/files/2480875/log.txt)

**Comment by valentinvanelslande** [comment]
tu ROM está corrupto

**Comment by Maxdex6** [comment]
que tendria que hacer? descargar uno nuevo?

**Comment by valentinvanelslande** [comment]
vuelve a dumpear el juego
