### ISSUE TITLE
Fire emblem warriors crashes 

### ISSUE THREAD

**Issue by greggo23** [citra-valentin/citra#477]
i used the latest version and the game crashes
![screenshot 67](https://user-images.githubusercontent.com/44216156/48383044-0f360100-e71f-11e8-840d-a15c76be89c8.png)

my pc version:
i5-7200U  CPU @2.71 Ghz 4Gb ram 64bit

**Comment by valentinvanelslande** [comment]
change model to one of the new models

**Comment by greggo23** [comment]
i don't understand please send me a detail

**Comment by valentinvanelslande** [comment]
change model to new 3ds
